# Generated by Django 5.1.5 on 2025-02-17 08:37

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('post_code', models.CharField(blank=True, max_length=10)),
                ('points', models.IntegerField(blank=True, default=0)),
                ('voucher', models.IntegerField(blank=True, default=0)),
                ('premium', models.BooleanField(default=False)),
                ('premium_issued_date', models.DateField(blank=True, null=True)),
                ('undefined_1', models.CharField(max_length=200)),
                ('undefined_2', models.CharField(max_length=200)),
                ('undefined_3', models.CharField(max_length=200)),
                ('undefined_4', models.CharField(max_length=200)),
                ('undefined_5', models.CharField(max_length=200)),
                ('undefined_6', models.CharField(max_length=200)),
                ('undefined_7', models.CharField(max_length=200)),
                ('undefined_8', models.CharField(max_length=200)),
                ('undefined_9', models.CharField(max_length=200)),
                ('undefined_10', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('price', models.FloatField(max_length=50)),
                ('cost', models.FloatField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('stream', models.CharField(blank=True, max_length=50)),
                ('section', models.CharField(blank=True, max_length=50)),
                ('bar_code', models.CharField(blank=True, max_length=50)),
                ('undefined_1', models.CharField(max_length=200)),
                ('undefined_2', models.CharField(max_length=200)),
                ('undefined_3', models.CharField(max_length=200)),
                ('undefined_4', models.CharField(max_length=200)),
                ('undefined_5', models.CharField(max_length=200)),
                ('undefined_6', models.CharField(max_length=200)),
                ('undefined_7', models.CharField(max_length=200)),
                ('undefined_8', models.CharField(max_length=200)),
                ('undefined_9', models.CharField(max_length=200)),
                ('undefined_10', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_unmber', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=10)),
                ('total_amount', models.FloatField(max_length=100)),
                ('order_status', models.IntegerField(choices=[(0, 'Canceled'), (1, 'Processing'), (2, 'Shipped'), (3, 'Collected')], default=1)),
                ('order_canceled', models.BooleanField(default=False)),
                ('undefined_1', models.CharField(max_length=200)),
                ('undefined_2', models.CharField(max_length=200)),
                ('undefined_3', models.CharField(max_length=200)),
                ('undefined_4', models.CharField(max_length=200)),
                ('undefined_5', models.CharField(max_length=200)),
                ('undefined_6', models.CharField(max_length=200)),
                ('undefined_7', models.CharField(max_length=200)),
                ('undefined_8', models.CharField(max_length=200)),
                ('undefined_9', models.CharField(max_length=200)),
                ('undefined_10', models.CharField(max_length=200)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
