# Generated by Django 5.1.5 on 2025-02-16 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('price', models.FloatField(max_length=50)),
                ('cost', models.FloatField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('stream', models.CharField(blank=True, max_length=50)),
                ('section', models.CharField(blank=True, max_length=50)),
                ('bar_code', models.CharField(blank=True, max_length=50)),
                ('undefined_1', models.CharField(max_length=200)),
                ('undefined_2', models.CharField(max_length=200)),
                ('undefined_3', models.CharField(max_length=200)),
                ('undefined_4', models.CharField(max_length=200)),
                ('undefined_5', models.CharField(max_length=200)),
                ('undefined_6', models.CharField(max_length=200)),
                ('undefined_7', models.CharField(max_length=200)),
                ('undefined_8', models.CharField(max_length=200)),
                ('undefined_9', models.CharField(max_length=200)),
                ('undefined_10', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=10)),
                ('points', models.IntegerField(blank=True)),
                ('voucher', models.CharField(blank=True, max_length=50)),
                ('premium', models.BooleanField(default=False)),
                ('premium_issued_date', models.DateField(blank=True, max_length=50)),
                ('undefined_1', models.CharField(max_length=200)),
                ('undefined_2', models.CharField(max_length=200)),
                ('undefined_3', models.CharField(max_length=200)),
                ('undefined_4', models.CharField(max_length=200)),
                ('undefined_5', models.CharField(max_length=200)),
                ('undefined_6', models.CharField(max_length=200)),
                ('undefined_7', models.CharField(max_length=200)),
                ('undefined_8', models.CharField(max_length=200)),
                ('undefined_9', models.CharField(max_length=200)),
                ('undefined_10', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_unmber', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=10)),
                ('total_amount', models.FloatField(max_length=100)),
                ('order_status', models.IntegerField(choices=[(0, 'canceled'), (1, 'processing'), (2, 'shipped'), (3, 'collected')], default=1)),
                ('order_canceled', models.BooleanField(default=False)),
                ('undefined_1', models.CharField(max_length=200)),
                ('undefined_2', models.CharField(max_length=200)),
                ('undefined_3', models.CharField(max_length=200)),
                ('undefined_4', models.CharField(max_length=200)),
                ('undefined_5', models.CharField(max_length=200)),
                ('undefined_6', models.CharField(max_length=200)),
                ('undefined_7', models.CharField(max_length=200)),
                ('undefined_8', models.CharField(max_length=200)),
                ('undefined_9', models.CharField(max_length=200)),
                ('undefined_10', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
            ],
        ),
    ]
