# Generated by Django 5.1.5 on 2025-02-17 10:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('price', models.FloatField(max_length=50)),
                ('cost', models.FloatField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('stream', models.CharField(blank=True, max_length=50)),
                ('section', models.CharField(blank=True, max_length=50)),
                ('bar_code', models.CharField(blank=True, max_length=50)),
                ('undefined_1', models.CharField(max_length=200)),
                ('undefined_2', models.CharField(max_length=200)),
                ('undefined_3', models.CharField(max_length=200)),
                ('undefined_4', models.CharField(max_length=200)),
                ('undefined_5', models.CharField(max_length=200)),
                ('undefined_6', models.CharField(max_length=200)),
                ('undefined_7', models.CharField(max_length=200)),
                ('undefined_8', models.CharField(max_length=200)),
                ('undefined_9', models.CharField(max_length=200)),
                ('undefined_10', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('post_code', models.CharField(blank=True, max_length=10)),
                ('points', models.IntegerField(blank=True, default=0)),
                ('voucher', models.IntegerField(blank=True, default=0)),
                ('premium', models.BooleanField(default=False)),
                ('premium_issued_date', models.DateField(blank=True, null=True)),
                ('undefined_1', models.CharField(max_length=200)),
                ('undefined_2', models.CharField(max_length=200)),
                ('undefined_3', models.CharField(max_length=200)),
                ('undefined_4', models.CharField(max_length=200)),
                ('undefined_5', models.CharField(max_length=200)),
                ('undefined_6', models.CharField(max_length=200)),
                ('undefined_7', models.CharField(max_length=200)),
                ('undefined_8', models.CharField(max_length=200)),
                ('undefined_9', models.CharField(max_length=200)),
                ('undefined_10', models.CharField(max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_unmber', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=10)),
                ('total_amount', models.FloatField(max_length=100)),
                ('order_status', models.IntegerField(choices=[(0, 'Canceled'), (1, 'Processing'), (2, 'Shipped'), (3, 'Collected')], default=1)),
                ('order_canceled', models.BooleanField(default=False)),
                ('undefined_1', models.CharField(max_length=200)),
                ('undefined_2', models.CharField(max_length=200)),
                ('undefined_3', models.CharField(max_length=200)),
                ('undefined_4', models.CharField(max_length=200)),
                ('undefined_5', models.CharField(max_length=200)),
                ('undefined_6', models.CharField(max_length=200)),
                ('undefined_7', models.CharField(max_length=200)),
                ('undefined_8', models.CharField(max_length=200)),
                ('undefined_9', models.CharField(max_length=200)),
                ('undefined_10', models.CharField(max_length=200)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
