# Generated by Django 5.1.5 on 2025-02-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='points',
            field=models.IntegerField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Canceled'), (1, 'Processing'), (2, 'Shipped'), (3, 'Collected')], default=1),
        ),
    ]
