# Generated by Django 5.1.5 on 2025-02-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_order_items_order_items'),
    ]

    operations = [
    ]
