# Generated by Django 5.1.5 on 2025-02-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_customer_points_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='points',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='voucher',
            field=models.IntegerField(blank=True),
        ),
    ]
