# Generated by Django 5.1.5 on 2025-02-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_points_alter_customer_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='premium_issued_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
